-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 03:36:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema digisocialdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `digisocialdb` ;

-- -----------------------------------------------------
-- Schema digisocialdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `digisocialdb` DEFAULT CHARACTER SET utf8 ;
USE `digisocialdb` ;

-- -----------------------------------------------------
-- Table `digisocialdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digisocialdb`.`user` ;

CREATE TABLE IF NOT EXISTS `digisocialdb`.`user` (
  `us_id` INT NULL AUTO_INCREMENT,
  `us_username` VARCHAR(50) NOT NULL,
  `us_password` VARCHAR(50) NOT NULL,
  `us_email` VARCHAR(100) NOT NULL,
  `us_mobilenumber` INT NOT NULL,
  `us_joiningdatetime` DATETIME NOT NULL,
  `us_dateofbirth` DATETIME NOT NULL,
  `us_firstname` VARCHAR(50) NOT NULL,
  `us_lastname` VARCHAR(50) NOT NULL,
  `us_middlename` VARCHAR(50) NULL,
  UNIQUE INDEX `us_id_UNIQUE` (`us_id` ASC) VISIBLE,
  PRIMARY KEY (`us_username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digisocialdb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digisocialdb`.`chat` ;

CREATE TABLE IF NOT EXISTS `digisocialdb`.`chat` (
  `ch_id` INT NOT NULL AUTO_INCREMENT,
  `ch_fromuser` VARCHAR(50) NOT NULL,
  `ch_touser` VARCHAR(50) NOT NULL,
  `ch_chatfilename` VARCHAR(104) NOT NULL,
  PRIMARY KEY (`ch_id`),
  INDEX `ch_fromuser_idx` (`ch_fromuser` ASC) VISIBLE,
  INDEX `ch_touser_idx` (`ch_touser` ASC) VISIBLE,
  CONSTRAINT `ch_fromuser`
    FOREIGN KEY (`ch_fromuser`)
    REFERENCES `digisocialdb`.`user` (`us_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ch_touser`
    FOREIGN KEY (`ch_touser`)
    REFERENCES `digisocialdb`.`user` (`us_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digisocialdb`.`friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digisocialdb`.`friend` ;

CREATE TABLE IF NOT EXISTS `digisocialdb`.`friend` (
  `fr_id` INT NOT NULL AUTO_INCREMENT,
  `fr_us_username` VARCHAR(50) NOT NULL,
  `fr_us_fr_username` VARCHAR(50) NOT NULL,
  `fr_isfriend` TINYINT NOT NULL DEFAULT 0,
  `fr_req_send_accept_declined` CHAR(1) NOT NULL,
  PRIMARY KEY (`fr_id`),
  INDEX `fr_us_username_idx` (`fr_us_username` ASC) VISIBLE,
  INDEX `fr_us_fr_username_idx` (`fr_us_fr_username` ASC) VISIBLE,
  CONSTRAINT `fr_us_username`
    FOREIGN KEY (`fr_us_username`)
    REFERENCES `digisocialdb`.`user` (`us_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fr_us_fr_username`
    FOREIGN KEY (`fr_us_fr_username`)
    REFERENCES `digisocialdb`.`user` (`us_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digisocialdb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digisocialdb`.`post` ;

CREATE TABLE IF NOT EXISTS `digisocialdb`.`post` (
  `po_id` INT NOT NULL AUTO_INCREMENT,
  `po_byusername` VARCHAR(50) NOT NULL,
  `po_caption` VARCHAR(1000) NULL,
  `po_imagefilename` VARCHAR(200) NULL,
  `po_datetime` DATETIME NOT NULL,
  `po_ispost` TINYINT NOT NULL,
  PRIMARY KEY (`po_id`),
  INDEX `po_byusername_idx` (`po_byusername` ASC) VISIBLE,
  CONSTRAINT `po_byusername`
    FOREIGN KEY (`po_byusername`)
    REFERENCES `digisocialdb`.`user` (`us_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digisocialdb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digisocialdb`.`comment` ;

CREATE TABLE IF NOT EXISTS `digisocialdb`.`comment` (
  `co_id` INT NOT NULL AUTO_INCREMENT,
  `co_po_id` INT NOT NULL,
  `co_byusername` VARCHAR(50) NOT NULL,
  `co_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`co_id`),
  INDEX `co_po_id_idx` (`co_po_id` ASC) VISIBLE,
  INDEX `co_byusername_idx` (`co_byusername` ASC) VISIBLE,
  CONSTRAINT `co_po_id`
    FOREIGN KEY (`co_po_id`)
    REFERENCES `digisocialdb`.`post` (`po_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `co_byusername`
    FOREIGN KEY (`co_byusername`)
    REFERENCES `digisocialdb`.`user` (`us_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
